fixed restoring forces formulation
Robotic-Decision-Making-Lab/hydrodynamics pull request #4
Opened 2024-05-16 23:55 UTC by Eddy-Morgan

## Changes Made

The rotation matrix `rot` is now transposed before being applied to the force vectors `fg` and `fb`, ensuring correct force calculations as per guidelines in Thor Fossen's Handbook of Marine Craft.

## Associated Issues

- Fixes # (issue)

2024-05-25 08:09 UTC, evan-palmer requested changes
Nice catch @Eddy-Morgan! Thanks for bringing this up and submitting a fix. I apologize for not submitting a review earlier. I didn't get a notification of this PR for some reason. I've left one comment for us to think about

2024-05-25 23:39 UTC, Eddy-Morgan commented on src/hydrodynamics.cpp
> +  g_rb.topRows(3) = rot.transpose() * (fg + fb);
Both approaches are viable. However, to maintain adherence to the Fossen formulation, I recommend modifying the function to mirror the transformation method detailed in his book. This adjustment ensure consistency with his established standards and enhance the clarity of the code.

The suggested code snippet looks excellent:

`const Eigen::Matrix3d rot_t = rot.transpose()
g_rb.topRows(3) = rot_t * (fg + fb);
// etc`

2024-05-25 23:46 UTC, evan-palmer commented on src/hydrodynamics.cpp
> +  g_rb.topRows(3) = rot.transpose() * (fg + fb);
Great lets go with that approach then

2024-05-26 00:45 UTC, evan-palmer approved these changes

2024-05-26 00:46 UTC, evan-palmer commented
Looks good! Thanks for contributing @Eddy-Morgan!

2024-05-26 00:46 UTC, merged