Modified construction of rigid body inertia and coriolis matrices
Robotic-Decision-Making-Lab/hydrodynamics pull request #8
Opened 2024-10-30 20:35 UTC by rakeshv24

## Changes Made

Included the computation for the off-diagonal terms of the rigid body inertia and Coriolis matrices based on the equations presented in [1] and [2].

[1] Fossen, T.I., 2011. Handbook of marine craft hydrodynamics and motion control. John Willy & Sons Ltd.
[2] Antonelli, G., 2014. Underwater Robots, volume 96 of Springer Tracts in Advanced Robotics.

2024-10-31 02:13 UTC, evan-palmer requested changes

2024-10-31 02:13 UTC, evan-palmer commented on include/hydrodynamics/hydrodynamics.hpp
> +    const Eigen::Vector3d & center_of_gravity);
Lets create a new constructor that supports this instead of modifying the existing constructor.

2024-10-31 02:13 UTC, evan-palmer commented on include/hydrodynamics/hydrodynamics.hpp
> +  Inertia(
Dito

2024-10-31 02:13 UTC, evan-palmer commented on include/hydrodynamics/hydrodynamics.hpp
> +  Coriolis(double mass, const Eigen::Vector3d & moments, Eigen::Vector6d added_mass, Eigen::Vector3d center_of_gravity);
Dito

2024-10-31 05:18 UTC, rakeshv24 commented on include/hydrodynamics/hydrodynamics.hpp
> +    const Eigen::Vector3d & center_of_gravity);
Sounds good!

2024-10-31 05:31 UTC, rakeshv24 commented on include/hydrodynamics/hydrodynamics.hpp
> +  Coriolis(double mass, const Eigen::Vector3d & moments, Eigen::Vector6d added_mass, Eigen::Vector3d center_of_gravity);
@evan-palmer In the case of inertia matrix, it is being computed inside the constructor itself. However for Coriolis, I plan to use `center_of_gravity` [here](https://github.com/Robotic-Decision-Making-Lab/hydrodynamics/blob/1238dff568fe53d28defb8c41c5fca4fc51276cd/src/hydrodynamics.cpp#L125-L128). If the user calls the wrong constructor, then `center_of_gravity` won't be defined. Please correct me if I am wrong.

2024-10-31 07:29 UTC, evan-palmer commented on include/hydrodynamics/hydrodynamics.hpp
> +  Coriolis(double mass, const Eigen::Vector3d & moments, Eigen::Vector6d added_mass, Eigen::Vector3d center_of_gravity);
You can just initialize it to zero in the original constructor

2024-11-01 01:19 UTC, evan-palmer requested changes

2024-11-01 01:19 UTC, evan-palmer commented on src/hydrodynamics.cpp
> +  center_of_gravity = Eigen::Vector3d::Zero();
This can be moved to the initializer list

2024-11-01 03:02 UTC, evan-palmer approved these changes
Looks good! Thanks!

2024-11-01 03:02 UTC, merged